# Generated by Django 5.2.17 on 2026-10-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('scenario_id', models.CharField(db_index=True, max_length=20)),
                ('choice', models.CharField(max_length=1)),
                ('first_choice', models.CharField(blank=True, max_length=1, null=True)),
                ('decision_ms', models.IntegerField()),
                ('hover_ms', models.JSONField()),
                ('changed_answer', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'responses',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scenarios',
                'ordering': ['created_at'],
            },
        ),
    ]
