# Generated by Django 5.2.17 on 2026-10-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='final_select_ms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='max_deviation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='mouse_path',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='path_length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='position',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='stay_on_left',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='x_flips',
            field=models.IntegerField(null=True),
        ),
    ]
