# Generated by Django 5.2.17 on 2026-10-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_study_design_and_mouse_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('key', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'rate_limits',
            },
        ),
    ]
