# Generated by Django 5.2.17 on 2026-10-02 16:57

from django.db import migrations, models


def remove_duplicate_answers(apps, schema_editor):
    """Before adding the one-answer-per-scenario rule: if a session answered a scenario more than once,
    keep its first answer and delete the later ones (otherwise the rule couldn't be added)."""
    Response = apps.get_model("poll", "Response")
    seen = set()
    duplicates = []
    for answer in Response.objects.order_by("id").only("id", "session_id", "scenario_id").iterator():
        pair = (answer.session_id, answer.scenario_id)
        if pair in seen:
            duplicates.append(answer.id)
        seen.add(pair)
    Response.objects.filter(id__in=duplicates).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_shared_rate_limit'),
    ]

    operations = [
        # Earlier rate-limit counts were keyed by the raw IP address; they only last 10 minutes, so drop them.
        migrations.RunSQL("DELETE FROM rate_limits", reverse_sql=migrations.RunSQL.noop),
        migrations.RunPython(remove_duplicate_answers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('session_id', 'scenario_id'), name='one_answer_per_scenario'),
        ),
    ]
